export const SET_FILMS = 'SET_FILMS';
export const SET_FILMS_LOADING = 'SET_FILMS_LOADING';
export const SET_FILMS_ERROR = 'SET_FILMS_ERROR';
export const SET_FILM_TO_FAVORITES = 'SET_FILM_TO_FAVORITES';
export const REMOVE_FILM_FROM_FAVORITES = 'REMOVE_FILM_FROM_FAVORITES';
